version: '3'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  db:
    restart: always
    image: postgres
    ports:
      - "5432:5432"

    environment:
      - DEBUG=false

      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
