# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 13:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('air_date', models.DateField()),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('genres', django.contrib.postgres.fields.jsonb.JSONField()),
                ('show_type', models.CharField(max_length=20)),
                ('premiered', models.IntegerField()),
                ('image', models.URLField()),
                ('creators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('tv_rage_id', models.IntegerField()),
                ('language', models.CharField(max_length=20)),
                ('networks', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tv_rage_rating', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('schedule', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('actors', models.ManyToManyField(to='actors.Actor')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.TvShow'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.Season'),
        ),
    ]
